### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by dennishumes** [AndreiD/Flask-Easy-Template#4]
got the following error in attempting to deploy:- 
 Invalid requirement: 'aniso8601 (1.1.0)'
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
           req = REQUIREMENT.parseString(requirement_string)
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
           raise exc
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
           loc, tokens = self._parse( instring, 0 )
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
           loc,tokens = self.parseImpl( instring, preloc, doActions )
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
           loc, exprtokens = e._parse( instring, loc, doActions )
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
           loc,tokens = self.parseImpl( instring, preloc, doActions )
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
           raise ParseException(instring, loc, self.errmsg, self)
       pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 10), (line:1, col:11)
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
           req = Requirement(req)
         File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
           requirement_string[e.loc:e.loc + 8]))
       pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'(1.1.0)'"
       
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by cheikhnadiouf** [comment]
Some hosting services like heroku if i remembered require a special procedure **when you get an Error parsing in requirements.txt**
As you can see in README.md a section called "TROUBLESHOOTS"  is talking about that (maybe it will help you to fix this issue) : 

**- Error parsing in requirements.txt ?**
    Run instead this compatible formatted file :
        python -m pip install -r requirements-pip2.txt    
    or convert first your requirements.txt to a python 2 pip2 compatible format with this command :
        python -m pip list --format=freeze > requirements.txt
